version: "3.7"

services:
  proxy:
    build: .
    image: node:12-alpine
    working_dir: /seller-reviews-proxy
    command: sh -c "npm install --production"
    ports:
      - "80:3000"
    restart: always
    volumes:
      - ./:/seller-reviews-proxy
    command: sh -c "npm start"